// import { DivMousePosition } from './useDivMousePosition.js';
import { ThrottleDebounce } from './useThrottleDebounce.js';
import { DotAContextMenu } from './useDotAContextMenu.js';
import { GetWindowScrollVal } from './useGetWindowScrollVal.js';
// import { GetDomScrollVal } from './useGetDomScrollVal.js';
import { ImgLoad } from './useImgLoad.js';
// export const useDivMousePosition = DivMousePosition;
export const useThrottleDebounce = ThrottleDebounce; 
export const useDotAContextMenu = DotAContextMenu; 
export const useGetWindowScrollVal = GetWindowScrollVal; 
// export const useGetDomScrollVal = GetDomScrollVal; 
export const useImgLoad = ImgLoad; 